apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: medishield
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: medishield
  labels: { app: mysql }
spec:
  replicas: 1
  strategy: { type: Recreate }
  selector:
    matchLabels: { app: mysql }
  template:
    metadata:
      labels: { app: mysql }
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: medishield
            - name: MYSQL_USER
              value: medishield
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef: { name: medishield-secrets, key: MYSQL_PASSWORD }
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef: { name: medishield-secrets, key: MYSQL_ROOT_PASSWORD }
          resources:
            requests: { memory: "400Mi", cpu: "100m" }
            limits:   { memory: "1Gi",   cpu: "500m" }
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mysql-data
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: medishield
spec:
  selector: { app: mysql }
  ports:
    - port: 3306
      targetPort: 3306
